---
development: 
  password: bcf0bcab74e1db6b560f55e1cb7ea9e9
  store: sectional-test.myshopify.com
  theme_id: 70500933 
  whitelist_files:
    - layout/
    - assets/
    - config/
    - snippets/
    - sections/
    - templates/
    - locales/
  ignore_files:
    - config/settings_data.json
